FROM python:slim
WORKDIR /usr/src/app
COPY ./src/ .
COPY requirements.txt ./
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "./features.py"]
